apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-acx-ui
data:
  google.maps.key: "AIzaSyB2tIww5SYmX8xjJVdzEUIuwtZyS5TXnhI"
  split.io.key: "dt1vi86ncfjjh04k8e4gp8auf6v41iutk4su"
  disable.pendo: "true"
  enable.contextqa: "false"
  captive.portal.domain.name: "scale.ruckus.cloud"
  new.api.domain.name: "api.scale.ruckus.cloud"
  api.documentation.url: "https://support.ruckuswireless.com/documents/4485"

