apiVersion: v1
kind: ConfigMap
metadata:
  name: mlisa-core-rsa-mlisa-ui-config
data:
  MLISA_UI_USER_TRACKING: b775f526-720b-449c-7fca-f45b7c3df0ae
  MLISA_VERSION: v4.14.1
  PENDO_API_KEY: b775f526-720b-449c-7fca-f45b7c3df0ae
