apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-rc-ui-acx
data:
    captive.portal.domain.name: "intalto.ruckuswireless.com"
    google.maps.key: "AIzaSyB39cAm6pQ7R8xRtcJNDWUxLjWPKGT_jHQ"
    splitio.ff.key: "54426nn43sd814m9drt1lg1jeupgr06jd9st"

