apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-acx-ui
data:
  captive.portal.domain.name: "intalto.ruckuswireless.com"
  google.maps.key: "AIzaSyB39cAm6pQ7R8xRtcJNDWUxLjWPKGT_jHQ"
  split.io.key: "54426nn43sd814m9drt1lg1jeupgr06jd9st"

