apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-acx-ui
data:
  captive.portal.domain.name: "int.ruckus.cloud"
  google.maps.key: "AIzaSyB39cAm6pQ7R8xRtcJNDWUxLjWPKGT_jHQ"
  split.io.key: "54426nn43sd814m9drt1lg1jeupgr06jd9st"
  splitproxy.cs.endpoint: "https://splitproxy.int.ruckus.cloud"
  new.api.domain.name: "api.int.ruckus.cloud"
  api.documentation.url: "https://support.ruckuswireless.com/documents/4485"

