apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-acx-ui
data:
  google.maps.key: "AIzaSyDq4QI2gdhGotqFiR28ZXk_RkbWtZ-IMDQ"
  split.io.key: "s56i5harnvpksqb6a5kom1phqncj9d6ujf92"
  pendo.api.key: "b775f526-720b-449c-7fca-f45b7c3df0ae"
  disable.pendo: "false"
  captive.portal.domain.name: "devalto.ruckuswireless.com"
  change.password: "https://supportqa.ruckuswireless.com/edit_my_profile"
  manage.licenses: "https://supportqa.ruckuswireless.com/cloud_subscriptions"
  fetchbot.js.url: "https://storage.googleapis.com/tdi-static/chat/tdi-uat-latest.min.js"
