apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-acx-ui
data:
  google.maps.key: "AIzaSyDq4QI2gdhGotqFiR28ZXk_RkbWtZ-IMDQ"
  split.io.key: "s56i5harnvpksqb6a5kom1phqncj9d6ujf92"
  pendo.api.key: "b775f526-720b-449c-7fca-f45b7c3df0ae"
  disable.pendo: "false"
  captive.portal.domain.name: "dev.ruckus.cloud"
  change.password: "https://support-uat.ruckuswireless.com/edit_my_profile"
  manage.licenses: "https://support-uat.ruckuswireless.com/cloud_subscriptions"
  fetchbot.js.url: "https://storage.googleapis.com/tdi-static/chat/tdi-uat-latest.min.js"
  documentation.center: "https://docs.cloud.ruckuswireless.com/ruckusone/releasenotes/releasenotes.html"
  my.open.cases: "https://support.ruckuswireless.com/cases/cloud"
  privacy: "https://www.commscope.com/about-us/privacy-statement"
  supported.ap.models: "https://www.ruckusnetworks.com/ruckus-one-supported-network-devices"
  how.to.videos: "https://www.youtube.com/playlist?list=PLySwoo7u9-KLJteXD3vhjK20eDQDp7NoP"
  new.api.domain.name: "api.dev.ruckus.cloud"
  static.assets: "https://storage.googleapis.com/ruckus-web-1"
  api.documentation.url: "https://support.ruckuswireless.com/documents/4485"
