apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: alto
resources:
  - configmap-acx-ui.yaml
  - values-acx-ui.yaml
  - values-configmap-env-map-acx-ui.yaml
  - values-configmap-vol-map-acx-ui.yaml
  - values-secret-env-map-acx-ui.yaml
  - values-secret-vol-map-acx-ui.yaml
