apiVersion: v1
kind: ConfigMap
metadata:
  name: values-configmap-env-map-acx-ui
data:
  values.yaml: |
    service:
      configmaps:
      - configmap: configmap-acx-ui
        key: google.maps.key
        name: GOOGLE_MAPS_KEY
      - configmap: configmap-acx-ui
        key: split.io.key
        name: SPLIT_IO_KEY
      - configmap: configmap-splitproxy
        key: splitproxy-cs-endpoint
        name: SPLIT_PROXY_ENDPOINT
      - configmap: configmap-acx-ui
        key: pendo.api.key
        name: PENDO_API_KEY
      - configmap: configmap-acx-ui
        key: disable.pendo
        name: DISABLE_PENDO
      - configmap: configmap-acx-ui
        key: captive.portal.domain.name
        name: CAPTIVE_PORTAL_DOMAIN_NAME
      - configmap: configmap-acx-ui
        key:  change.password
        name: CHANGE_PASSWORD
      - configmap: configmap-acx-ui
        key: manage.licenses
        name: MANAGE_LICENSES
      - configmap: configmap-acx-ui
        key: fetchbot.js.url
        name: FETCHBOT_JS_URL
      - configmap: configmap-acx-ui
        key: documentation.center
        name: DOCUMENTATION_CENTER
      - configmap: configmap-acx-ui
        key: my.open.cases
        name: MY_OPEN_CASES
      - configmap: configmap-acx-ui
        key: privacy
        name: PRIVACY
      - configmap: configmap-acx-ui
        key: supported.ap.models
        name: SUPPORTED_AP_MODELS
      - configmap: configmap-acx-ui
        key: how.to.videos
        name: HOW_TO_VIDEOS
      - configmap: configmap-acx-ui
        key: new.api.domain.name
        name: NEW_API_DOMAIN_NAME
      - configmap: configmap-acx-ui
        key: static.assets
        name: STATIC_ASSETS
      - configmap: configmap-acx-ui
        key: api.documentation.url
        name: API_DOCUMENTATION_URL

