apiVersion: v1
kind: ConfigMap
metadata:
  name: values-configmap-env-map-acx-ui
data:
  values.yaml: |
    service:
      configmaps:
      - configmap: configmap-acx-ui
        key: google.maps.key
        name: GOOGLE_MAPS_KEY
