apiVersion: v1
kind: ConfigMap
metadata:
  name: values-configmap-vol-map-acx-ui
data:
  values.yaml: |
    # service:
    #   volumeMounts:
    #     initContainers:
    #       # this is the name of the initContainer
    #       rks-dbmigrate:
    #         name: config-volume
    #         mountPath: /etc/config
    #         readOnly: true
    #     containers:
    #       # this is the name of the Container
    #       acx-ui:
    #         name: config-volume
    #         mountPath: /etc/config
    #         readOnly: true
    #   volumes:
    #     - name: config-volume
    #       configMap:
    #         name: configmap-acx-ui
