apiVersion: v1
kind: ConfigMap
metadata:
  name: values-secret-vol-map-sample
data:
  values.yaml: |
    # service:
    #   volumeMounts:
    #     initContainers:
    #       # this is the name of the initContainer
    #       rks-dbmigrate:
    #         name: rks-db-secret-volume
    #         mountPath: /etc/secret
    #     containers:
    #       # this is the name of the Container
    #       sample-acx:
    #         name: rks-db-secret-volume
    #         mountPath: /etc/secret
    #   volumes:
    #     - name: rks-db-secret-volume
    #       secret:
    #         secretName: sample-rks-db
