apiVersion: v1
kind: ConfigMap
metadata:
  name: values-secret-env-map-acx-ui
data:
  values.yaml: |
    # service:
    #   secrets:
    #   - key: username
    #     name: SECRET_SAMPLE_RKS_DB_USERNAME
    #     secret: acx-ui-rks-db
    #   - key: password
    #     name: SECRET_SAMPLE_RKS_DB_PASSWORD
    #     secret: acx-ui-rks-db
