apiVersion: v1
kind: ConfigMap
metadata:
  name: values-configmap-env-map-acx-ui
data:
  values.yaml: |
    service:
      configmaps:
      - configmap: configmap-acx-ui
        key: google.maps.key
        name: GOOGLE_MAPS_KEY
      - configmap: configmap-acx-ui
        key: split.io.key
        name: SPLIT_IO_KEY
      - configmap: configmap-acx-ui
        key: pendo.api.key
        name: PENDO_API_KEY
      - configmap: configmap-acx-ui
        key: disable.pendo
        name: DISABLE_PENDO
      - configmap: configmap-acx-ui
        key: captive.portal.domain.name
        name: CAPTIVE_PORTAL_DOMAIN_NAME
      - configmap: configmap-acx-ui
        key:  change.password
        name: CHANGE_PASSWORD
      - configmap: configmap-acx-ui
        key: manage.licenses
        name: MANAGE_LICENSES