apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-acx-ui
data:
  google.maps.key: "AIzaSyBSIqtIaVqxpvP0mE3KSTohqpTV9CLuZaM"
  split.io.key: "7be0ne01vnli2nea8eekg4h0c5tmmmn63sa5"
  captive.portal.domain.name: "sg.ruckus.cloud"
  change.password: "https://support.ruckuswireless.com/edit_my_profile"
  manage.licenses: "https://support.ruckuswireless.com/cloud_subscriptions"
  fetchbot.js.url: "https://storage.googleapis.com/tdi-static/chat/tdi-prd-latest.min.js"
  new.api.domain.name: "api.sg.ruckus.cloud"
  api.documentation.url: "https://support.ruckuswireless.com/documents/4485"
