apiVersion: v1
kind: ConfigMap
metadata:
  name: values-secret-vol-map-acx-ui
data:
  values.yaml: |
#   service:
#     volumeMounts:
#       initcontainers:
#         rks-dbmigrate:
#          - name: config-volume
#            mountPath: /etc/config/db
#            readOnly: true
#       containers:
#         acx-ui:
#          - name: secret-volume-acx-ui
#            mountPath: /etc/config/secret
#            readOnly: true
#     volumes:
#       - name: secret-volume-acx-ui
#         secret:
#           secretName: secret-acx-ui
