apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-rc-ui-acx
data:
    google.maps.key: "AIzaSyAUtkFCkaAcJX-6e09ZytS_WBPpmSXMx8M"
    splitio.ff.key: "rgkslm2jd328tlh1ah1be4e8kcuqm824u511"
    captive.portal.domain.name: "qaalto.ruckuswireless.com"
