apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-rc-ui-acx
data:
    splitio.ff.key: "mv0ie7nqslfon47mabelfdloqdem1alfctqp"
    google.maps.key: "AIzaSyCO5O4se2-GDzFXqfUFAMDZHycyZfugqSc"
    captive.portal.domain.name: "stage.qaalto.ruckuswireless.com"
