apiVersion: v1
kind: ConfigMap
metadata:
  name: mlisa-core-rsa-mlisa-ui-config
data:
  ASK_MLISA_URL: /api/a4rc/api/ask-mlisa
  DEPLOYMENT_MODE: ALTO
  DISABLE_PENDO: "true"
  DRUID_COLD_TIER_DAYS: "31"
  DRUID_RETAIN_PERIOD_DAYS: "90"
  DRUID_ROLLUP_DAYS: "36500"
  ENABLED_FEATURES: ask_mlisa|config_change|i_apinfra_poe_low|i_apinfra_wanthroughput_low|occupancy|schedule_report|sci_kafka_indexing|superset|sv_ota|sv_ota_3radios|superset_schedule|config_recommendation|rc_public_api|icx_analytics|ap-service-anomaly
  MLISA_BASE_URL_PREFIX: /api/a4rc
  MLISA_DATA_API_URL: /api/a4rc/api/rsa-data-api/graphql
  MLISA_DOCUMENTATION_URL: https://docs.cloud.ruckuswireless.com/alto/mapfile/index.html
  MLISA_GPT_URL: /api/a4rc/api/mlisa-gpt
  MLISA_LICENSE_URL: /api/a4rc/api/rsa-mlisa-licensing
  MLISA_LOGOUT_URL: /logout
  MLISA_NOTIFICATION_URL: /api/a4rc/api/rsa-mlisa-notification
  MLISA_OCCUPANCY_URL: /api/a4rc/api/rsa-mlisa-presence-api/graphql
  MLISA_RBAC_URL: /api/a4rc/api/rsa-mlisa-rbac
  MLISA_REGION: us-central1
  MLISA_SERVICE_GUARD_URL: /api/a4rc/api/rsa-mlisa-service-guard/graphql
  MLISA_SMARTZONE_MGR_URL: /api/a4rc/api/rsa-mlisa-smartzone/v1
  MLISA_SUPERSET_URL: /api/a4rc/explorer
  MLISA_UI_USER_TRACKING: <required>
  MLISA_VIDEO_CALL_QOE_URL: /api/a4rc/api/rsa-mlisa-call-manager/graphql
  NODE_OPTIONS: --max-old-space-size=2048 --max-http-header-size=262144
  PENDO_API_KEY: <required>
  SCI_REPORTS_FRAGMENT_URL: http://mlisa-core-rsa-ui-fragments.mlisa-core.svc.cluster.local:5100
  STATIC_ASSETS: https://storage.googleapis.com/ruckus-web-1
