apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-acx-ui
data:
  google.maps.key: "AIzaSyAWQnu3C-y2DsQIQmixgQNFp6UjQdvDFFo"
  split.io.key: "jj5d5r9hnhvb3avsroeiplbdp3rn7glvoei8"
  captive.portal.domain.name: "asia.ruckus.cloud"
  change.password: "https://support.ruckuswireless.com/edit_my_profile"
  manage.licenses: "https://support.ruckuswireless.com/cloud_subscriptions"
  fetchbot.js.url: "https://storage.googleapis.com/tdi-static/chat/tdi-prd-latest.min.js"
