apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-rc-ui-acx
data:
    google.maps.key: "AIzaSyAWQnu3C-y2DsQIQmixgQNFp6UjQdvDFFo"
    disable.pendo: "true"
    splitio.ff.key: "jj5d5r9hnhvb3avsroeiplbdp3rn7glvoei8"
    captive.portal.domain.name: "asia.ruckus.cloud"
