- configs_dir: acx-ui
  chart:
    name: acx_standard1
  values_configmaps:
    - values-configmap-vol-map-acx-ui
    - values-secret-vol-map-acx-ui
      #- values-acx-ui
  # following must match the default value.yaml in the Helm chart
  service:
    name: acx-ui
    image:
      path: gcr.io/kumo-scratch/services/acx-ui/ui
