apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-acx-ui
data:
  enable.contextqa: "true"
  contextqa.key: "phc_WIcDskiqCroNW6JNdTbjMRbb51aO5dLVMbXKot7ZRxZ"
  contextqa.tenants: "[\"6b43a3a62c964826b44bc97beb550fba\",\"c7746b3cf9794a55a6b6c2fa4b00a6d2\",\"396787eb8aad421f8511092c0a16c838\",\"056e3c92bb5a49338c3df0778e47d3a6\",\"c724e66b2a5243a5adec324c7eab9f14\",\"138ddb275fbb432db2d55548e86199a9\",\"2f5e7fdc44b74b7480117129a168e320\",\"17f0b6ef890e419191d1586f228096dd\",\"eae80308c3d344a9a4468c3cd0a18e98\",\"b36cb485bae9416196c440baa310ceb7\",\"bbfc2eb48502449c8bafe8ee574d470b\",\"bfdd15cd062c4990914ef9c20b770851\",\"6f25bcaed1d84d028fef87d29059087f\",\"572ca6083d884b358927dec50a88b70f\",\"512bd620312147628b55253e6e8f9db6\",\"62f55c6693054fc59c994a88ba6be6ff\",\"cd561187406c439b8c7b13786adadce0\",\"17661629bf1e4d8c993e7f64a4822c26\"]"