apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-acx-ui
data:
  google.maps.key: "AIzaSyB2tIww5SYmX8xjJVdzEUIuwtZyS5TXnhI"
  split.io.key: "im8eg8833nmbkhasp485oja5j0ktku22e1mh"
  disable.pendo: "true"
  captive.portal.domain.name: "eu.qaalto.ruckuswireless.com"
  new.api.domain.name: "api.eu.qaalto.ruckuswireless.com"
  api.documentation.url: "https://support.ruckuswireless.com/documents/4485"
