apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-acx-ui
data:
  google.maps.key: "AIzaSyACjGDfnC5-HTRbG5dVkJp7hDRpRVwqp4M"
  split.io.key: "im8eg8833nmbkhasp485oja5j0ktku22e1mh"
  splitproxy.cs.endpoint: "https://splitproxy.qaeu.ruckus.cloud"
  captive.portal.domain.name: "eu.qaalto.ruckuswireless.com"
  new.api.domain.name: "api.eu.qaalto.ruckuswireless.com"
  api.documentation.url: "https://support.ruckuswireless.com/documents/4485"
