apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-acx-ui
data:
    google.maps.key: "AIzaSyACjGDfnC5-HTRbG5dVkJp7hDRpRVwqp4M"
    disable.pendo: "true"
    splitio.ff.key: "im8eg8833nmbkhasp485oja5j0ktku22e1mh"
    captive.portal.domain.name: "eu.qaalto.ruckuswireless.com"
