apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-acx-ui
data:
  google.maps.key: "AIzaSyB2tIww5SYmX8xjJVdzEUIuwtZyS5TXnhI"
  split.io.key: "mlbj64qb8lgfji5upnedt4lo7h5c4ik65m95"
  captive.portal.domain.name: "stage.ruckus.cloud"
  change.password: "https://support.ruckuswireless.com/edit_my_profile"
  manage.licenses: "https://support.ruckuswireless.com/cloud_subscriptions"
  new.api.domain.name: "api.stage.ruckus.cloud"
  api.documentation.url: "https://support.ruckuswireless.com/documents/4485"
  druid.retain.period.days: "380"