apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-acx-ui
data:
  google.maps.key: "AIzaSyCpQ4EbLcktRsOYx_UemIY5ZvIMgB6P-mo"
  split.io.key: "mlbj64qb8lgfji5upnedt4lo7h5c4ik65m95"
  captive.portal.domain.name: "opsalto.ruckuswireless.com"
  change.password: "https://support.ruckuswireless.com/edit_my_profile"
  manage.licenses: "https://support.ruckuswireless.com/cloud_subscriptions"
  new.api.domain.name: "api.opsalto.ruckuswireless.com"
  api.documentation.url: "https://support.ruckuswireless.com/documents/4485"
